apiVersion: v1
kind: Service
metadata:
  labels:
    app: fintech
    tag: fintech
  name: fintech
  namespace: default
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 8111
  selector:
    app: fintech
    tag: fintech
  type: ClusterIP
