apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fintech
      tag: fintech
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fintech
        tag: fintech
    spec:
      containers:
      - image: buinhattruong/fintech:v1.0.0
        imagePullPolicy: IfNotPresent
        name: fintech
